setClass("TopDownExperiment",
  slots=c(name="character",
          sequence="character",
          fragmentTable="data.table",
          assignmentTable="data.table"),
  contains=c("MSnExp"),
  prototype=prototype(new("MSnExp"),
                      name=character(),
                      sequence=character(),
                      fragmentTable=data.table(),
                      assignmentTable=data.table()),
  validity=function(object).validateTopDownExperiment(object)
)
