#' Add adducts to the output of MSnbase::calculateFragments
#'
#' @param x `data.frame`, output of [MSnbase::calculateFragments()]
#' @param adducts `data.frame`, with 3 columns mass, name, to
#' @return `data.frame`
#' @noRd
.addAdducts <- function(x, adducts) {
   if (!nrow(adducts)) {
       return(x)
   }

   if (!all(c("mass", "name", "to") %in% colnames(adducts))) {
       stop("The 'adducts' data.frame must have the columns: ",
            "'mass', 'name' and 'to'.")
   }

   r <- do.call(rbind, lapply(seq_len(nrow(adducts)), function(i) {
       a <- x[x$type == adducts$to[i], , drop=FALSE]
       a$mz <- a$mz + adducts$mass[i]
       a$ion <- paste0(adducts$name[i], a$pos)
       a
   }))
   x <- rbind(x, r)
   rownames(x) <- NULL
   x
}

#' Calculate Fragments (via MSnbase::calculateFragments)
#'
#' @param sequence `AAString`, peptide sequence
#' @param type `character`, type of fragments
#' @param modification `character`, unimod names
#' @param neutralLoss `list`, neutral loss (see [MSnbase::calculateFragments()])
#' @param adducts `data.frame`, with 3 columns mass, name, to
#' @param verbose `logical`, verbose output?
#' @return `FragmentViews`
#' @noRd
.calculateFragments <- function(sequence, type=c("a", "b", "c", "x", "y", "z"),
                                modifications=c("Carbamidomethyl",
                                                "Met-loss+Acetyl"),
                                neutralLoss=defaultNeutralLoss(),
                                adducts=data.frame(),
                                verbose=interactive()) {
    modifications <- match.arg(modifications,
                               choices=c("", # allow NULL for nothing
                                         "Carbamidomethyl",
                                         "Met-loss+Acetyl"),
                               several.ok=TRUE)
    csequence <- as.character(sequence)
    d <- calculateFragments(csequence,
                            type=type,
                            modifications=NULL,
                            neutralLoss=neutralLoss,
                            verbose=FALSE)
    ## TODO: replace by unimod package
    if ("Carbamidomethyl" %in% modifications) {
        d <- .unimod4(d)
    }
    ## TODO: replace by unimod package
    if ("Met-loss+Acetyl" %in% modifications) {
        sequence <- gsub("^M([ACGPSTV])", "\\1", sequence)
        csequence <- as.character(sequence)
        d <- .unimod766(d)
    }
    if (all(!nchar(modifications))) {
        modifications <- NULL
    }
    d <- .addAdducts(d, adducts)

    n <- nchar(sequence)
    FragmentViews(sequence, mass=d$mz, type=d$type, z=Rle(d$z), names=d$ion,
                  start=ifelse(startsWith(csequence, d$seq),
                               1L, n - d$pos + 1L),
                  width=d$pos, metadata=list(modifications=modifications))
}

#' Match fragments and measured mz values.
#'
#' @param mz `double`, measured mz.
#' @param fmass `double`, fragment mass
#' @param tolerance `double`, allowed tolerance
#' @return `integer`
#' @noRd
.matchFragments <- function(mz, fmass, tolerance=2.5e-5) {
  if (!length(mz)) {
    integer()
  }
  m <- MSnbase:::relaxedMatch(mz, fmass, nomatch=NA, tolerance=tolerance,
                              relative=TRUE)
  if (anyDuplicated(m)) {
    o <- order(abs(mz - fmass[m]))
    sortedMatches <- m[o]
    sortedMatches[which(duplicated(sortedMatches))] <- NA
    m[o] <- sortedMatches
  }
  as.integer(m)
}

#' Apply unimod modification 4:  Carbamidomethyl
#'
#' Carboxyamidomethylation
#'
#' TODO: replace by unimod package
#'
#' @param x `data.frame`, generated by [MSnbase::calculateFragments()]
#' @return modified `data.frame`
#' @noRd
.unimod4 <- function(x) {
    iCU <- grep("C|U", x$seq)
    x$mz[iCU] <- x$mz[iCU] + 57.021464
    x
}

#' Apply unimod modification 766: Met-loss+Acetyl
#'
#' N-terminal methionine removed if followed by A, C, G, P, S, T, or V
#' additional acetylated if A, G, S, T
#'
#' TODO: replace by unimod package
#'
#' @param x `data.frame`, generated by [MSnbase::calculateFragments()]
#' @return modified `data.frame`
#' @noRd
.unimod766 <- function(x) {
    x <- x[x$seq != "M", , drop=FALSE]
    iM <- grepl("^M[ACGPSTV]", x$seq)
    iAc <- grepl("^M[AGST]", x$seq)
    if (any(iM)) {
        x$pos[iM] <- x$pos[iM] - 1L
        ## can't use simple paste0/substr/gsub command because replacement could
        ## change number of digits and neutral loss has scheme x[0-9][_*]
        x$ion[iM] <- unlist(mapply(gsub,
                                   x=x$ion[iM],
                                   replacement=paste0(x$pos[iM], "\\1"),
                                   MoreArgs=list(pattern="[0-9]+([_*]?)$"),
                                   SIMPLIFY=FALSE, USE.NAMES=FALSE))
        x$seq[iM] <- substr(x$seq[iM], 2L, nchar(x$seq[iM]))
        x$mz[iM & !iAc] <- x$mz[iM & !iAc] - 131.040485
        x$mz[iAc] <- x$mz[iAc] - 89.029920
        ## remove duplicated sequences but keep the -M one
        x <- x[!(duplicated(x$ion) | duplicated(x$ion, fromLast=TRUE)) | iM, ]
        rownames(x) <- NULL
    }
    x
}
