#' Add adducts to the output of MSnbase::calculateFragments
#'
#' @param x `data.frame`, output of [MSnbase::calculateFragments()]
#' @param adducts `data.frame`, with 3 columns mass, name, to
#' @return `data.frame`
#' @noRd
.addAdducts <- function(x, adducts) {
   if (!nrow(adducts)) {
       return(x)
   }

   if (!all(c("mass", "name", "to") %in% colnames(adducts))) {
       stop("The 'adducts' data.frame must have the columns: ",
            "'mass', 'name' and 'to'.")
   }

   r <- do.call(rbind, lapply(seq_len(nrow(adducts)), function(i) {
       a <- x[x$type == adducts$to[i], , drop=FALSE]
       a$mz <- a$mz + adducts$mass[i]
       a$ion <- paste0(adducts$name[i], a$pos)
       a
   }))
   x <- rbind(x, r)
   rownames(x) <- NULL
   x
}

#' Calculate Fragments (via MSnbase::calculateFragments)
#'
#' @param sequence `AAString`, peptide sequence
#' @param type `character`, type of fragments
#' @param modification `character`, unimod names
#' @param neutralLoss `list`, neutral loss (see [MSnbase::calculateFragments()])
#' @param adducts `data.frame`, with 3 columns mass, name, to
#' @param verbose `logical`, verbose output?
#' @return `FragmentViews`
#' @noRd
.calculateFragments <- function(sequence, type=c("a", "b", "c", "x", "y", "z"),
                                modifications=c("Carbamidomethyl", "Acetyl",
                                                "Met-loss"),
                                neutralLoss=defaultNeutralLoss(),
                                adducts=data.frame(),
                                verbose=interactive()) {
    modifications <- match.arg(modifications,
                               choices=c("", # allow NULL for nothing
                                         "Carbamidomethyl",
                                         "Acetyl",
                                         "Met-loss"),
                               several.ok=TRUE)

    csequence <- as.character(sequence)
    ## TODO: replace by unimod package
    if ("Met-loss" %in% modifications) {
        csequence <- .unimod765(csequence)
    }

    d <- calculateFragments(csequence,
                            type=type,
                            modifications=NULL,
                            neutralLoss=neutralLoss,
                            verbose=FALSE)
    ## TODO: replace by unimod package
    if ("Acetyl" %in% modifications) {
        d <- .unimod1(d, csequence)
    }
    ## TODO: replace by unimod package
    if ("Carbamidomethyl" %in% modifications) {
        d <- .unimod4(d)
    }
    if (all(!nchar(modifications))) {
        modifications <- NULL
    }
    d <- .addAdducts(d, adducts)

    n <- nchar(csequence)
    FragmentViews(csequence, mass=d$mz, type=d$type, z=Rle(d$z), names=d$ion,
                  start=ifelse(startsWith(csequence, d$seq),
                               1L, n - d$pos + 1L),
                  width=d$pos, metadata=list(modifications=modifications))
}

#' Match fragments and measured mz values.
#'
#' @param mz `double`, measured mz.
#' @param fmass `double`, fragment mass
#' @param tolerance `double`, allowed tolerance
#' @return `integer`
#' @noRd
.matchFragments <- function(mz, fmass, tolerance=2.5e-5) {
  if (!length(mz)) {
    integer()
  }
  m <- MSnbase:::relaxedMatch(mz, fmass, nomatch=NA, tolerance=tolerance,
                              relative=TRUE)
  if (anyDuplicated(m)) {
    o <- order(abs(mz - fmass[m]))
    sortedMatches <- m[o]
    sortedMatches[which(duplicated(sortedMatches))] <- NA
    m[o] <- sortedMatches
  }
  as.integer(m)
}

#' Apply unimod modification 1: Acetyl
#'
#' Acetylation
#'
#' TODO: replace by unimod package
#'
#' @param x `data.frame`, generated by [MSnbase::calculateFragments()]
#' @param s `character`, sequence
#' @return modified `data.frame`
#' @noRd
.unimod1 <- function(x, s) {
    i <- startsWith(s, x$seq)
    x$mz[i] <- x$mz[i] + 42.010565
    x
}

#' Apply unimod modification 4:  Carbamidomethyl
#'
#' Carboxyamidomethylation
#'
#' TODO: replace by unimod package
#'
#' @param x `data.frame`, generated by [MSnbase::calculateFragments()]
#' @return modified `data.frame`
#' @noRd
.unimod4 <- function(x) {
    iCU <- grep("C|U", x$seq)
    x$mz[iCU] <- x$mz[iCU] + 57.021464
    x
}

#' Apply unimod modification 765: Met-loss
#'
#' N-terminal methionine removed if followed by A, C, G, P, S, T, or V
#'
#' TODO: replace by unimod package
#'
#' @param x `character`/`AAString`, sequence
#' @return `character`/`AAString` without ^M
#' @noRd
.unimod765 <- function(x) {
    gsub("^M([ACGPSTV])", "\\1", x)
}
